# Default values for fuseapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  namePrefix: time_A-
  image:
    tag: feature_01-dfc174aa6435d239e97ee0e928e07e
