@startuml

title Fluxo usando Jenkins + HELM de CICD no ambiente de PRODUÇÃO

autonumber

participant "source-code" as source << Bitbucket >> #LightGrey
participant Nexus as nexus << Repository >> #DarkCyan
participant "GitOps" as config << Bitbucket >> #Plum
participant "Jenkins" as jenkinsProd<< QA >> #LightGreen
participant "Openshift" as ocp << nodeSelector=AMBIENTE >>

== CD ==

[->jenkinsProd: JOB gerar Tag GitOps e RELEASE da IMAGEM - SEMPRE antes de promover PRODUÇÃO
activate jenkinsProd
jenkinsProd -> source: git MERGE VALIDATE ${BRANCH_NAME} com MASTER
note right: a depender do processo poderá abortar ou continuar

jenkinsProd -> config: gerarTagGit
jenkinsProd -> jenkinsProd: SNAPSHOT TO RELEASE
deactivate jenkinsProd

[-> jenkinsProd: JOB Aprovar para PRODUÇÃO (${TAG_NAME}))
activate jenkinsProd

jenkinsProd -> config: git clone branch ${AMBIENTE}
jenkinsProd --> jenkinsProd: TEMPLATE=${PROJETO}/${APP_NAME}
jenkinsProd --> jenkinsProd: helm template $TEMPLATE -f $TEMPLATE/values-PRD.yaml --output-dir target

jenkinsProd --> jenkinsProd: NAMESPACE=${PROJETO}-${AMBIENTE}
jenkinsProd -> ocp: oc -n ${NAMESPACE} apply -f -R target/
activate ocp
deactivate ocp
deactivate jenkinsProd

@enduml
